### PR TITLE
Group clock is always 80Mhz for idf > 5.2

### PR DESCRIPTION
**Pull request by boriszweimueller**
Starting with idf 5.3, the group frequency is always 80 MHz even when #define SDI12_RMT_CLK_SRC RMT_CLK_SRC_REF_TICK is set.
Not sure how to solve this correctly such that it works for different idf versions.

### CODE REVIEW

**Comment by jmpmscorp** [comment]
I haven't notice any change in RMT. Let me check 5.3 changelog.

**Comment by jmpmscorp** [comment]
@boriszweimueller What esp32 chip version are you using? I can't found any RMT change in 5.2+ versions that could affect library.

However, you must notice that RMT_CLK_SRC_REF_TICK is only defined in SOCs esp32 and esp32s2, so, if you are using any other chip, library will always use RMT_CLK_SRC_DEFAULT that is defined in every chip. You could check it in esp-idf source code in 'esp-idf/components/soc/{soc_version}/include/soc/clk_tree_defs.h'.

**Comment by boriszweimueller** [comment]
@jmpmscorp Thanks for your reply. Yes, I noticed these defines. I use an ESP32. But anyhow, the defined min signal range of 255 * 1000 always led to an assertion in rmt_rx.c => signal_range_min_ns too big. 
I did only had a very short look into the esp-idf source code and need to have a closer lock to exactly identify the differences to version <= 5.2.
You can easily reproduce this issue by just compiling your example with idf 5.3.

**Comment by jmpmscorp** [comment]
@boriszweimueller I have news.

If you read linked issue [RMT RX Filter...](https://github.com/espressif/esp-idf/issues/11262), it's supposed that If you set clk_src to RMT_CLK_SRC_REF_TICK, rmt group resolution is configured as 1Mhz. When you set filter range_min and range_max, clock source used is the same as rmt group use because clock is shared among every rmt channel in same group. Therefore, when I wrote lib, I calculated range_min and range_max with group frequency 1Mhz. As the SDI-12 bit time is 833us, I tried to adjust range_min_ns maximun to this value. But filter value is a 8-bit witdh so, that's why I set it to 255 ( 255us with group resolution 1Mhz). This value is far away from 833us but on tests was enough to work correctly.

However, deeping in rmt source code, I found this diffrence inside 'rmt_new_rx_channel' function:

ESP-IDF <5.2
```
// select the clock source
    ESP_GOTO_ON_ERROR(rmt_select_periph_clock(&rx_channel->base, config->clk_src), err, TAG, "set group clock failed");
    // set channel clock resolution
    uint32_t real_div = group->resolution_hz / config->resolution_hz;
    rmt_ll_rx_set_channel_clock_div(hal->regs, channel_id, real_div);
    // resolution loss due to division, calculate the real resolution
    rx_channel->base.resolution_hz = group->resolution_hz / real_div;
    if (rx_channel->base.resolution_hz != config->resolution_hz) {
        ESP_LOGW(TAG, "channel resolution loss, real=%"PRIu32, rx_channel->base.resolution_hz);
    }

    rmt_ll_rx_set_mem_blocks(hal->regs, channel_id, rx_channel->base.mem_block_num);
    rmt_ll_rx_set_mem_owner(hal->regs, channel_id, RMT_LL_MEM_OWNER_HW);
```

ESP-IDF >=5.2
```
     // select the clock source
    ESP_GOTO_ON_ERROR(rmt_select_periph_clock(&rx_channel->base, config->clk_src), err, TAG, "set group clock failed");
    // set channel clock resolution
    uint32_t real_div = group->resolution_hz / config->resolution_hz;
    rmt_ll_rx_set_channel_clock_div(hal->regs, channel_id, real_div);
    // resolution loss due to division, calculate the real resolution
    rx_channel->base.resolution_hz = group->resolution_hz / real_div;
    if (rx_channel->base.resolution_hz != config->resolution_hz) {
        ESP_LOGW(TAG, "channel resolution loss, real=%"PRIu32, rx_channel->base.resolution_hz);
    }

    rx_channel->filter_clock_resolution_hz = group->resolution_hz;
    // On esp32 and esp32s2, the counting clock used by the RX filter always comes from APB clock
    // no matter what the clock source is used by the RMT channel as the "core" clock
#if CONFIG_IDF_TARGET_ESP32 || CONFIG_IDF_TARGET_ESP32S2
    esp_clk_tree_src_get_freq_hz(SOC_MOD_CLK_APB, ESP_CLK_TREE_SRC_FREQ_PRECISION_CACHED, &rx_channel->filter_clock_resolution_hz);
#endif

    rmt_ll_rx_set_mem_blocks(hal->regs, channel_id, rx_channel->base.mem_block_num);
    rmt_ll_rx_set_mem_owner(hal->regs, channel_id, RMT_LL_MEM_OWNER_HW);
```

As you can check, since 5.2, on esp32 and esp32s2 filter clock is always APB (80Mhz) ignoring crk_src configured on RX channel.

Consequently, since 5.2, when rmt filter_reg_value is calculated
```
uint32_t filter_reg_value = ((uint64_t)rx_chan->filter_clock_resolution_hz * config->signal_range_min_ns) / 1000000000UL;
```

```filter_clock_resolution_hz``` is 80Mhz, not 1Mhz supposed before 5.2. That's why you see range_min_ns exceed value error.

With that in mind, if filter clock frenquency is always 80Mhz, range_min_ns maximun value is 3186ns (1 / 80000000 * 255). For the moment, I will set signal_range_min_ns fixed to this value and I will ask espressif how to set greater values.

I have tested my SDI-12 sensor with scanner example and work great. I would appreciate if you could test new changes with yours.

Regards.

**Comment by boriszweimueller** [comment]
@jmpmscorp Thanks for digging in the source code and finding the difference between before/after 5.2. I can confirm, it works perfectly with the singal_range_min_ns of 3186!
Best Regards

**Pull request closed without merging**
